"""Trading strategy: mean reversion at daily S/R zones.

Refined strategy rules (from all 30 NickShawnFX videos):
1. Identify zones on WEEKLY/DAILY chart
2. Enter on 1-HOUR chart when price is INSIDE the zone and a reversal candle appears
3. Price must be at least HALFWAY into the zone before entry
4. Configured risk-to-reward ratio (default 1.2R target)
5. Stop loss beyond zone + all recent wicks + breathing room
6. CUT LOSSES EARLY: zone break, sideways action, time limit, structure break
7. HOLD WINNERS: don't close early (exception: Friday close near TP)
8. CORRELATION: cap simultaneous correlated exposure
9. MOMENTUM FILTER: skip entries with strong momentum into zone
"""

from dataclasses import dataclass, field
from typing import FrozenSet, List, Optional, Set
import pandas as pd

from .levels import SRZone, is_price_in_zone, is_price_halfway_in_zone
from .config import (
    PAIRS,
    DEFAULT_RR_RATIO,
    DEFAULT_SL_BUFFER_PCT,
    DEFAULT_EARLY_EXIT_R,
    DEFAULT_COOLDOWN_BARS,
    DEFAULT_MIN_ENTRY_CANDLE_BODY_PCT,
    DEFAULT_MOMENTUM_LOOKBACK,
    DEFAULT_MAX_CORRELATED_TRADES,
    DEFAULT_EXECUTION_SPREAD_PIPS,
    DEFAULT_STOP_SLIPPAGE_PIPS,
    DEFAULT_PIVOT_WINDOW,
    DEFAULT_CLUSTER_TOL,
)


# Correlation groups: pairs sharing a currency tend to move together
CORRELATION_GROUPS = {
    'USD': ['EURUSD', 'GBPUSD', 'AUDUSD', 'NZDUSD', 'USDCHF', 'USDCAD', 'USDJPY'],
    'JPY': ['USDJPY', 'EURJPY', 'GBPJPY', 'AUDJPY', 'CADJPY', 'CHFJPY', 'NZDJPY'],
    'EUR': ['EURUSD', 'EURGBP', 'EURJPY', 'EURAUD', 'EURCAD', 'EURCHF'],
    'GBP': ['GBPUSD', 'EURGBP', 'GBPJPY', 'GBPAUD', 'GBPCAD', 'GBPCHF'],
    'AUD': ['AUDUSD', 'AUDJPY', 'EURAUD', 'GBPAUD', 'AUDNZD', 'AUDCAD'],
    'CAD': ['USDCAD', 'CADJPY', 'EURCAD', 'GBPCAD', 'AUDCAD'],
    'CHF': ['USDCHF', 'CHFJPY', 'EURCHF', 'GBPCHF'],
    'NZD': ['NZDUSD', 'NZDJPY', 'AUDNZD'],
}


def get_correlated_pairs(pair: str) -> set:
    """Return set of pairs correlated with the given pair."""
    correlated = set()
    for group, members in CORRELATION_GROUPS.items():
        if pair in members:
            correlated.update(members)
    correlated.discard(pair)
    return correlated


@dataclass
class Signal:
    """A trading signal generated by the strategy."""
    time: pd.Timestamp
    pair: str
    direction: str      # 'LONG' or 'SHORT'
    entry_price: float
    sl_price: float
    tp_price: float
    zone_upper: float
    zone_lower: float
    zone_strength: str
    zone_type: str


@dataclass
class Trade:
    """A completed or open trade."""
    entry_time: pd.Timestamp
    entry_price: float
    direction: str
    sl_price: float
    tp_price: float
    zone_upper: float
    zone_lower: float
    zone_strength: str
    risk: float             # dollar distance of full risk (entry to SL)
    exit_time: Optional[pd.Timestamp] = None
    exit_price: Optional[float] = None
    exit_reason: Optional[str] = None   # 'TP', 'SL', 'EARLY_EXIT', 'SIDEWAYS', 'TIME', 'FRIDAY', 'END'
    pnl_pips: float = 0.0
    pnl_r: float = 0.0     # P&L in R-multiples
    bars_held: int = 0      # 1H bars the trade was open


"""Pair+direction combos with historically poor win rates (<29%)."""
BLOCKED_PAIR_DIRECTIONS = {
    ('USDCAD', 'SHORT'),   # 16.1% WR
    ('USDCAD', 'LONG'),    # 0% WR (30-day)
    ('AUDUSD', 'SHORT'),   # 22.4% WR
    ('EURGBP', 'SHORT'),   # 25.0% WR
    ('USDCHF', 'LONG'),    # 28.6% WR
    ('GBPUSD', 'SHORT'),   # 28.6% WR
    ('NZDUSD', 'LONG'),    # 0% WR (30-day)
    ('NZDUSD', 'SHORT'),   # 0% WR (30-day)
    ('GBPJPY', 'LONG'),    # 0% WR (30-day)
    ('GBPJPY', 'SHORT'),   # 0% WR (30-day)
    # New crosses — poor performers
    ('GBPCAD', 'LONG'),    # 18% WR
    ('GBPCAD', 'SHORT'),   # 18% WR
    ('CADJPY', 'LONG'),    # 29% WR
    ('CADJPY', 'SHORT'),   # 29% WR
    ('EURCAD', 'LONG'),    # 17% WR
    ('EURCAD', 'SHORT'),   # 17% WR
    ('AUDJPY', 'LONG'),    # 0% WR
    ('AUDJPY', 'SHORT'),   # 0% WR
    ('EURCHF', 'LONG'),    # 0% WR
    ('EURCHF', 'SHORT'),   # 0% WR
    ('AUDCAD', 'LONG'),    # 33% WR marginal
    ('AUDCAD', 'SHORT'),   # 33% WR marginal
}

"""Default hours with historically poor win rates (<25%)."""
DEFAULT_BLOCKED_HOURS: FrozenSet[int] = frozenset({2, 3})  # 02:00-03:00 UTC

"""Default days with historically poor win rates."""
DEFAULT_BLOCKED_DAYS: FrozenSet[int] = frozenset()  # none blocked (Monday unblocked for optimized preset)

# Keep module-level aliases for backward compatibility with imports
BLOCKED_HOURS = DEFAULT_BLOCKED_HOURS
BLOCKED_DAYS = DEFAULT_BLOCKED_DAYS


@dataclass
class StrategyParams:
    """Tunable strategy parameters."""
    rr_ratio: float = DEFAULT_RR_RATIO          # tuned reward multiple
    sl_buffer_pct: float = DEFAULT_SL_BUFFER_PCT # % buffer beyond zone for SL
    early_exit_r: float = DEFAULT_EARLY_EXIT_R   # close losers at this R-multiple
    spread_pips: float = DEFAULT_EXECUTION_SPREAD_PIPS  # explicit spread on midpoint bars
    stop_slippage_pips: float = DEFAULT_STOP_SLIPPAGE_PIPS  # extra adverse stop fill
    min_zone_touches: int = 3                    # minimum touches for a tradeable zone
    zone_penetration_pct: float = 0.50            # fraction of zone price must penetrate (0.5=halfway)
    pivot_window: int = DEFAULT_PIVOT_WINDOW      # bars left/right for pivot detection
    cluster_tolerance: float = DEFAULT_CLUSTER_TOL  # % tolerance for clustering pivots
    zone_windows: tuple = (180,)                  # lookback windows (days) for zone detection
    cooldown_bars: int = DEFAULT_COOLDOWN_BARS  # 1H bars between trades
    max_hold_bars: int = 72                      # ~3 days max hold without progress
    sideways_bars: int = 15                      # ~15 hours of sideways = exit
    sideways_threshold: float = 0.3              # must move 30% toward TP or considered sideways
    momentum_lookback: int = DEFAULT_MOMENTUM_LOOKBACK  # bars to check momentum into zone
    momentum_threshold: float = 0.7              # body/range ratio for strong momentum candle
    friday_tp_pct: float = 0.70                  # close winners on Friday if 70%+ to TP
    use_correlation_filter: bool = True           # enforce correlation limits
    max_correlated_trades: int = DEFAULT_MAX_CORRELATED_TRADES  # cap correlated exposure
    use_pair_direction_filter: bool = True        # block bad pair+direction combos
    use_time_filters: bool = True                # block bad hours and days
    min_entry_candle_body_pct: float = DEFAULT_MIN_ENTRY_CANDLE_BODY_PCT  # min body/range ratio for entry candle
    blocked_hours: FrozenSet[int] = DEFAULT_BLOCKED_HOURS
    blocked_days: FrozenSet[int] = DEFAULT_BLOCKED_DAYS


def get_pair_pip(pair: str) -> float:
    """Return pip size for the given pair."""
    return PAIRS.get(pair, {}).get('pip', 0.0001)


def get_half_spread_price(pip: float, params: StrategyParams) -> float:
    """Return half-spread in price terms for midpoint-to-executable conversion."""
    return max(params.spread_pips, 0.0) * pip / 2.0


def get_entry_execution_price(mid_price: float, direction: str, pip: float, params: StrategyParams) -> float:
    """Convert a midpoint bar close into a realistic executable entry price."""
    half_spread = get_half_spread_price(pip, params)
    if direction == 'LONG':
        return mid_price + half_spread
    return mid_price - half_spread


def get_market_exit_price(mid_price: float, direction: str, pip: float, params: StrategyParams) -> float:
    """Convert a midpoint bar close into a realistic executable market exit price."""
    half_spread = get_half_spread_price(pip, params)
    if direction == 'LONG':
        return mid_price - half_spread
    return mid_price + half_spread


def get_stop_exit_price(stop_price: float, direction: str, pip: float, params: StrategyParams) -> float:
    """Apply adverse stop slippage to the configured stop level."""
    slippage = max(params.stop_slippage_pips, 0.0) * pip
    if direction == 'LONG':
        return stop_price - slippage
    return stop_price + slippage


def generate_signal(
    bar_open: float,
    bar_close: float,
    bar_high: float,
    bar_low: float,
    zone: SRZone,
    pair: str,
    time: pd.Timestamp,
    params: StrategyParams,
) -> Optional[Signal]:
    """Check if a 1-hour candle inside a zone produces an entry signal.

    Entry criteria (from video):
    1. Price must be inside the zone
    2. Price must have penetrated at least halfway into the zone
    3. A reversal candle must appear:
       - At support: bullish candle (close > open)
       - At resistance: bearish candle (close < open)

    Args:
        bar_open/close/high/low: 1-hour candle values
        zone: the S/R zone being tested
        pair: pair identifier
        time: candle timestamp
        params: strategy parameters

    Returns:
        Signal if entry conditions met, None otherwise
    """
    if zone.touches < params.min_zone_touches:
        return None

    # Price must be inside the zone
    if not is_price_in_zone(bar_close, zone):
        return None

    # Price must penetrate sufficiently into the zone
    if not is_price_halfway_in_zone(bar_close, zone, params.zone_penetration_pct):
        return None

    # Entry candle quality: body must be meaningful relative to range
    candle_range = abs(bar_high - bar_low)
    candle_body = abs(bar_close - bar_open)
    if candle_range > 0 and candle_body / candle_range < params.min_entry_candle_body_pct:
        return None  # doji / indecision candle -> skip

    pip = get_pair_pip(pair)

    if zone.zone_type == 'support':
        # Bullish reversal candle at support -> LONG
        if bar_close <= bar_open:
            return None  # not bullish

        entry_price = get_entry_execution_price(bar_close, 'LONG', pip, params)
        sl = zone.lower * (1 - params.sl_buffer_pct / 100)
        risk = entry_price - sl
        if risk <= 0:
            return None
        tp = entry_price + risk * params.rr_ratio

        return Signal(
            time=time, pair=pair, direction='LONG',
            entry_price=entry_price, sl_price=sl, tp_price=tp,
            zone_upper=zone.upper, zone_lower=zone.lower,
            zone_strength=zone.strength, zone_type='support',
        )

    elif zone.zone_type == 'resistance':
        # Bearish reversal candle at resistance -> SHORT
        if bar_close >= bar_open:
            return None  # not bearish

        entry_price = get_entry_execution_price(bar_close, 'SHORT', pip, params)
        sl = zone.upper * (1 + params.sl_buffer_pct / 100)
        risk = sl - entry_price
        if risk <= 0:
            return None
        tp = entry_price - risk * params.rr_ratio

        return Signal(
            time=time, pair=pair, direction='SHORT',
            entry_price=entry_price, sl_price=sl, tp_price=tp,
            zone_upper=zone.upper, zone_lower=zone.lower,
            zone_strength=zone.strength, zone_type='resistance',
        )

    return None


def check_momentum_filter(
    hourly_df: pd.DataFrame,
    bar_idx: int,
    zone: SRZone,
    params: StrategyParams,
) -> bool:
    """Check if recent candles show strong momentum INTO the zone.

    Per videos: skip entries where price is approaching the zone with
    very strong momentum / large candles (high break-through probability).

    Returns True if momentum is too strong (should SKIP the entry).
    """
    lookback = params.momentum_lookback
    if bar_idx < lookback:
        return False

    strong_count = 0
    for j in range(bar_idx - lookback, bar_idx):
        row = hourly_df.iloc[j]
        candle_range = abs(row['High'] - row['Low'])
        if candle_range == 0:
            continue
        body = abs(row['Close'] - row['Open'])
        body_ratio = body / candle_range

        # Strong candle = large body relative to range
        if body_ratio >= params.momentum_threshold:
            # Check direction: is this momentum TOWARD the zone?
            if zone.zone_type == 'support' and row['Close'] < row['Open']:
                strong_count += 1  # strong bearish candle approaching support
            elif zone.zone_type == 'resistance' and row['Close'] > row['Open']:
                strong_count += 1  # strong bullish candle approaching resistance

    # If majority of recent candles are strong momentum toward zone, skip
    return strong_count >= lookback


def check_exit(
    trade: Trade,
    bar_high: float,
    bar_low: float,
    bar_close: float,
    bar_time: pd.Timestamp,
    bars_held: int,
    params: StrategyParams,
    pip: float,
    progress_toward_tp: float = 0.0,
) -> Optional[tuple[str, float]]:
    """Check if a trade should be exited.

    Enhanced exit rules (from all 30 videos):
    1. TP hit -> close at TP (hold winners)
    2. Friday close -> if winning and 70%+ to TP on Friday
    3. SL hit -> close at SL (emergency protection)
    4. EARLY EXIT: price breaks through zone -> close at partial loss
    5. SIDEWAYS: no progress after ~15 bars -> close at current price
    6. TIME: held too long (~72 bars / 3 days) without TP -> close

    Uses conservative midpoint-bar execution assumptions:
    - spread is modeled explicitly on entries and market exits
    - TP requires the midpoint to clear half-spread beyond the target
    - SL can trigger half-spread before the midpoint touches the stop level
    - if both TP and SL print in the same bar, resolve to SL

    Returns:
        (exit_reason, exit_price) tuple, or None if trade stays open
    """
    del progress_toward_tp  # legacy arg retained for compatibility

    early_exit_r = max(params.early_exit_r, 0.0)
    half_spread = get_half_spread_price(pip, params)
    market_exit = get_market_exit_price(bar_close, trade.direction, pip, params)

    if trade.direction == 'LONG':
        tp_hit = bar_high >= trade.tp_price + half_spread
        sl_hit = bar_low <= trade.sl_price + half_spread

        if tp_hit and sl_hit:
            return ('SL', get_stop_exit_price(trade.sl_price, trade.direction, pip, params))
        if tp_hit:
            return ('TP', trade.tp_price)

        # Friday close: if winning and 70%+ to TP
        if hasattr(bar_time, 'weekday') and bar_time.weekday() == 4:  # Friday
            if market_exit > trade.entry_price:
                tp_dist = trade.tp_price - trade.entry_price
                if tp_dist > 0:
                    current_progress = (market_exit - trade.entry_price) / tp_dist
                    if current_progress >= params.friday_tp_pct:
                        return ('FRIDAY', market_exit)

        if sl_hit:
            return ('SL', get_stop_exit_price(trade.sl_price, trade.direction, pip, params))

        # Early exit: zone break or a loss beyond the configured early-exit threshold.
        loss_r = ((trade.entry_price - market_exit) / trade.risk) if trade.risk > 0 else 0.0
        if bar_close < trade.zone_lower or loss_r >= early_exit_r:
            return ('EARLY_EXIT', market_exit)

        # Sideways exit: no meaningful progress after sideways_bars
        if bars_held >= params.sideways_bars and market_exit <= trade.entry_price:
            tp_dist = trade.tp_price - trade.entry_price
            if tp_dist > 0:
                progress = max(0.0, (market_exit - trade.entry_price) / tp_dist)
                if progress < params.sideways_threshold:
                    return ('SIDEWAYS', market_exit)

        # Time-based exit: held too long without resolution
        if bars_held >= params.max_hold_bars and market_exit <= trade.entry_price:
            return ('TIME', market_exit)

    else:  # SHORT
        tp_hit = bar_low <= trade.tp_price - half_spread
        sl_hit = bar_high >= trade.sl_price - half_spread

        if tp_hit and sl_hit:
            return ('SL', get_stop_exit_price(trade.sl_price, trade.direction, pip, params))
        if tp_hit:
            return ('TP', trade.tp_price)

        # Friday close: if winning and 70%+ to TP
        if hasattr(bar_time, 'weekday') and bar_time.weekday() == 4:  # Friday
            if market_exit < trade.entry_price:
                tp_dist = trade.entry_price - trade.tp_price
                if tp_dist > 0:
                    current_progress = (trade.entry_price - market_exit) / tp_dist
                    if current_progress >= params.friday_tp_pct:
                        return ('FRIDAY', market_exit)

        if sl_hit:
            return ('SL', get_stop_exit_price(trade.sl_price, trade.direction, pip, params))

        # Early exit: zone break or a loss beyond the configured early-exit threshold.
        loss_r = ((market_exit - trade.entry_price) / trade.risk) if trade.risk > 0 else 0.0
        if bar_close > trade.zone_upper or loss_r >= early_exit_r:
            return ('EARLY_EXIT', market_exit)

        # Sideways exit
        if bars_held >= params.sideways_bars and market_exit >= trade.entry_price:
            tp_dist = trade.entry_price - trade.tp_price
            if tp_dist > 0:
                progress = max(0.0, (trade.entry_price - market_exit) / tp_dist)
                if progress < params.sideways_threshold:
                    return ('SIDEWAYS', market_exit)

        # Time-based exit
        if bars_held >= params.max_hold_bars and market_exit >= trade.entry_price:
            return ('TIME', market_exit)

    return None
