"""Trading strategy: mean reversion at daily S/R zones.

Refined strategy rules (from all 30 NickShawnFX videos):
1. Identify zones on WEEKLY/DAILY chart
2. Enter on 1-HOUR chart when price is INSIDE the zone and a reversal candle appears
3. Price must be at least HALFWAY into the zone before entry
4. Configured risk-to-reward ratio (default 1.2R target)
5. Stop loss beyond zone + all recent wicks + breathing room
6. CUT LOSSES EARLY: zone break, sideways action, time limit, structure break
7. HOLD WINNERS: don't close early (exception: Friday close near TP)
8. CORRELATION: cap simultaneous correlated exposure
9. MOMENTUM FILTER: skip entries with strong momentum into zone
"""

from dataclasses import dataclass, field
from typing import FrozenSet, List, Optional, Set
import pandas as pd

from .levels import SRZone, is_price_in_zone, is_price_halfway_in_zone
from .config import (
    PAIRS,
    DEFAULT_RR_RATIO,
    DEFAULT_SL_BUFFER_PCT,
    DEFAULT_EARLY_EXIT_R,
    DEFAULT_COOLDOWN_BARS,
    DEFAULT_MIN_ENTRY_CANDLE_BODY_PCT,
    DEFAULT_MOMENTUM_LOOKBACK,
    DEFAULT_MAX_CORRELATED_TRADES,
    DEFAULT_EXECUTION_SPREAD_PIPS,
    DEFAULT_STOP_SLIPPAGE_PIPS,
    DEFAULT_PIVOT_WINDOW,
    DEFAULT_CLUSTER_TOL,
)
from .profiles import CORRELATION_GROUPS


def get_correlated_pairs(pair: str) -> set:
    """Return set of pairs correlated with the given pair."""
    correlated = set()
    for group, members in CORRELATION_GROUPS.items():
        if pair in members:
            correlated.update(members)
    correlated.discard(pair)
    return correlated


@dataclass
class Signal:
    """A trading signal generated by the strategy."""
    time: pd.Timestamp
    pair: str
    direction: str      # 'LONG' or 'SHORT'
    entry_price: float
    sl_price: float
    tp_price: float
    zone_upper: float
    zone_lower: float
    zone_strength: str
    zone_type: str
    quality_score: float = 0.0


@dataclass
class Trade:
    """A completed or open trade."""
    entry_time: pd.Timestamp
    entry_price: float
    direction: str
    sl_price: float
    tp_price: float
    zone_upper: float
    zone_lower: float
    zone_strength: str
    risk: float             # dollar distance of full risk (entry to SL)
    exit_time: Optional[pd.Timestamp] = None
    exit_price: Optional[float] = None
    exit_reason: Optional[str] = None   # 'TP', 'SL', 'EARLY_EXIT', 'SIDEWAYS', 'TIME', 'FRIDAY', 'END'
    pnl_pips: float = 0.0
    pnl_r: float = 0.0     # P&L in R-multiples
    bars_held: int = 0      # 1H bars the trade was open
    quality_score: float = 0.0


from .profiles import BLOCKED_PAIR_DIRECTIONS

"""Default hours with historically poor win rates (<25%)."""
DEFAULT_BLOCKED_HOURS: FrozenSet[int] = frozenset({2, 3})  # 02:00-03:00 UTC

"""Default days with historically poor win rates."""
DEFAULT_BLOCKED_DAYS: FrozenSet[int] = frozenset()  # none blocked (Monday unblocked for optimized preset)

# Keep module-level aliases for backward compatibility with imports
BLOCKED_HOURS = DEFAULT_BLOCKED_HOURS
BLOCKED_DAYS = DEFAULT_BLOCKED_DAYS


@dataclass
class StrategyParams:
    """Tunable strategy parameters."""
    rr_ratio: float = DEFAULT_RR_RATIO          # tuned reward multiple
    sl_buffer_pct: float = DEFAULT_SL_BUFFER_PCT # % buffer beyond zone for SL
    early_exit_r: float = DEFAULT_EARLY_EXIT_R   # close losers at this R-multiple
    spread_pips: float = DEFAULT_EXECUTION_SPREAD_PIPS  # explicit spread on midpoint bars
    stop_slippage_pips: float = DEFAULT_STOP_SLIPPAGE_PIPS  # extra adverse stop fill
    min_zone_touches: int = 3                    # minimum touches for a tradeable zone
    zone_penetration_pct: float = 0.50            # fraction of zone price must penetrate (0.5=halfway)
    pivot_window: int = DEFAULT_PIVOT_WINDOW      # bars left/right for pivot detection
    cluster_tolerance: float = DEFAULT_CLUSTER_TOL  # % tolerance for clustering pivots
    zone_windows: tuple = (180,)                  # lookback windows (days) for zone detection
    cooldown_bars: int = DEFAULT_COOLDOWN_BARS  # 1H bars between trades
    max_hold_bars: int = 72                      # ~3 days max hold without progress
    sideways_bars: int = 15                      # ~15 hours of sideways = exit
    sideways_threshold: float = 0.3              # must move 30% toward TP or considered sideways
    momentum_lookback: int = DEFAULT_MOMENTUM_LOOKBACK  # bars to check momentum into zone
    momentum_threshold: float = 0.7              # body/range ratio for strong momentum candle
    friday_tp_pct: float = 0.70                  # close winners on Friday if 70%+ to TP
    use_correlation_filter: bool = True           # enforce correlation limits
    max_correlated_trades: int = DEFAULT_MAX_CORRELATED_TRADES  # cap correlated exposure
    use_pair_direction_filter: bool = True        # block bad pair+direction combos
    use_time_filters: bool = True                # block bad hours and days
    min_entry_candle_body_pct: float = DEFAULT_MIN_ENTRY_CANDLE_BODY_PCT  # min body/range ratio for entry candle
    blocked_hours: FrozenSet[int] = DEFAULT_BLOCKED_HOURS
    blocked_days: FrozenSet[int] = DEFAULT_BLOCKED_DAYS
    streak_pause_trigger: int = 0              # pause entries after this many consecutive portfolio losses (0=off)
    streak_pause_hours: int = 24               # hours to skip entries after streak trigger fires
    loss_cooldown_bars: int = 0                # extra cooldown bars after a losing trade on the same pair (0=off)
    dynamic_risk: bool = False                 # enable equity-curve dynamic risk sizing
    dd_risk_start: float = 5.0                 # DD% at which risk starts scaling down
    dd_risk_full: float = 18.0                 # DD% at which risk hits the floor
    dd_risk_floor: float = 0.5                 # minimum risk% during deep drawdown
    # Quick bounce / linger filter
    max_linger_bars: int = 0                   # skip entry if price lingered at zone this many bars (0=off)
    linger_lookback: int = 8                   # how far back to check for lingering
    # Zone exhaustion
    zone_exhaustion_threshold: int = 0         # skip if zone visited X+ times recently (0=off)
    zone_exhaustion_lookback: int = 50         # 1H bars to check for recent visits
    # Quality-based risk scaling
    quality_sizing: bool = False               # enable quality-based risk scaling
    quality_risk_min: float = 0.5              # risk multiplier for lowest quality (0.5x base)
    quality_risk_max: float = 1.5              # risk multiplier for highest quality (1.5x base)
    # Correlation quality selection
    correlation_prefer_quality: bool = False    # prefer higher-quality trades in correlation filter
    # Submit-time live execution guards
    max_submit_quote_age_seconds: float = 2.0  # reject stale submit-time quotes
    max_submit_spread_pips: float = 2.0        # reject wide spreads at submit time
    max_submit_entry_drift_r: float = 0.25     # reject entries drifting too far from planned R
    prefer_l2_submit_quote: bool = True        # prefer L2 top-of-book over L1 when available
    # Historical execution parity
    strict_backtest_execution: bool = False    # require historical execution quotes for backtests
    allow_h1_execution_fallback: bool = True   # allow next-hour modeled fallback when quote data is missing


def params_from_profile(profile: dict, **overrides) -> 'StrategyParams':
    """Build a StrategyParams from a profile dict (from profiles.py).

    Any keyword arguments override the profile values.
    """
    merged = {**profile, **overrides}
    return StrategyParams(
        rr_ratio=merged['rr_ratio'],
        sl_buffer_pct=merged['sl_buffer_pct'],
        early_exit_r=merged['early_exit_r'],
        spread_pips=merged['spread_pips'],
        stop_slippage_pips=merged['stop_slippage_pips'],
        min_zone_touches=merged.get('min_zone_touches', 3),
        zone_penetration_pct=merged.get('zone_penetration_pct', 0.50),
        pivot_window=merged.get('pivot_window', DEFAULT_PIVOT_WINDOW),
        cluster_tolerance=merged.get('cluster_tolerance', DEFAULT_CLUSTER_TOL),
        zone_windows=(merged.get('zone_history_days', 180),),
        cooldown_bars=merged['cooldown_bars'],
        max_hold_bars=merged.get('max_hold_bars', 72),
        sideways_bars=merged.get('sideways_bars', 15),
        sideways_threshold=merged.get('sideways_threshold', 0.3),
        momentum_lookback=merged['momentum_lookback'],
        momentum_threshold=merged.get('momentum_threshold', 0.7),
        friday_tp_pct=merged.get('friday_tp_pct', 0.70),
        use_correlation_filter=merged.get('use_correlation_filter', True),
        max_correlated_trades=merged['max_correlated_trades'],
        use_pair_direction_filter=merged.get('use_pair_direction_filter', True),
        use_time_filters=merged.get('use_time_filters', True),
        min_entry_candle_body_pct=merged['min_entry_candle_body_pct'],
        blocked_hours=frozenset(merged.get('blocked_hours', [2, 3])),
        blocked_days=frozenset(merged.get('blocked_days', [])),
        streak_pause_trigger=merged.get('streak_pause_trigger', 0),
        streak_pause_hours=merged.get('streak_pause_hours', 24),
        loss_cooldown_bars=merged.get('loss_cooldown_bars', 0),
        dynamic_risk=merged.get('dynamic_risk', False),
        dd_risk_start=merged.get('dd_risk_start', 5.0),
        dd_risk_full=merged.get('dd_risk_full', 18.0),
        dd_risk_floor=merged.get('dd_risk_floor', 0.5),
        max_linger_bars=merged.get('max_linger_bars', 0),
        linger_lookback=merged.get('linger_lookback', 8),
        zone_exhaustion_threshold=merged.get('zone_exhaustion_threshold', 0),
        zone_exhaustion_lookback=merged.get('zone_exhaustion_lookback', 50),
        quality_sizing=merged.get('quality_sizing', False),
        quality_risk_min=merged.get('quality_risk_min', 0.5),
        quality_risk_max=merged.get('quality_risk_max', 1.5),
        correlation_prefer_quality=merged.get('correlation_prefer_quality', False),
        max_submit_quote_age_seconds=merged.get('max_submit_quote_age_seconds', 2.0),
        max_submit_spread_pips=merged.get('max_submit_spread_pips', 2.0),
        max_submit_entry_drift_r=merged.get('max_submit_entry_drift_r', 0.25),
        prefer_l2_submit_quote=merged.get('prefer_l2_submit_quote', True),
        strict_backtest_execution=merged.get('strict_backtest_execution', False),
        allow_h1_execution_fallback=merged.get('allow_h1_execution_fallback', True),
    )


def get_pair_pip(pair: str) -> float:
    """Return pip size for the given pair."""
    return PAIRS.get(pair, {}).get('pip', 0.0001)


def get_half_spread_price(pip: float, params: StrategyParams) -> float:
    """Return half-spread in price terms for midpoint-to-executable conversion."""
    return max(params.spread_pips, 0.0) * pip / 2.0


def get_entry_execution_price(mid_price: float, direction: str, pip: float, params: StrategyParams) -> float:
    """Convert a midpoint bar close into a realistic executable entry price."""
    half_spread = get_half_spread_price(pip, params)
    if direction == 'LONG':
        return mid_price + half_spread
    return mid_price - half_spread


def get_market_exit_price(mid_price: float, direction: str, pip: float, params: StrategyParams) -> float:
    """Convert a midpoint bar close into a realistic executable market exit price."""
    half_spread = get_half_spread_price(pip, params)
    if direction == 'LONG':
        return mid_price - half_spread
    return mid_price + half_spread


def get_stop_exit_price(stop_price: float, direction: str, pip: float, params: StrategyParams) -> float:
    """Apply adverse stop slippage to the configured stop level."""
    slippage = max(params.stop_slippage_pips, 0.0) * pip
    if direction == 'LONG':
        return stop_price - slippage
    return stop_price + slippage


def generate_signal(
    bar_open: float,
    bar_close: float,
    bar_high: float,
    bar_low: float,
    zone: SRZone,
    pair: str,
    time: pd.Timestamp,
    params: StrategyParams,
) -> Optional[Signal]:
    """Check if a 1-hour candle inside a zone produces an entry signal.

    Entry criteria (from video):
    1. Price must be inside the zone
    2. Price must have penetrated at least halfway into the zone
    3. A reversal candle must appear:
       - At support: bullish candle (close > open)
       - At resistance: bearish candle (close < open)

    Args:
        bar_open/close/high/low: 1-hour candle values
        zone: the S/R zone being tested
        pair: pair identifier
        time: candle timestamp
        params: strategy parameters

    Returns:
        Signal if entry conditions met, None otherwise
    """
    if zone.touches < params.min_zone_touches:
        return None

    # Price must be inside the zone
    if not is_price_in_zone(bar_close, zone):
        return None

    # Price must penetrate sufficiently into the zone
    if not is_price_halfway_in_zone(bar_close, zone, params.zone_penetration_pct):
        return None

    # Entry candle quality: body must be meaningful relative to range
    candle_range = abs(bar_high - bar_low)
    candle_body = abs(bar_close - bar_open)
    if candle_range > 0 and candle_body / candle_range < params.min_entry_candle_body_pct:
        return None  # doji / indecision candle -> skip

    pip = get_pair_pip(pair)

    if zone.zone_type == 'support':
        # Bullish reversal candle at support -> LONG
        if bar_close <= bar_open:
            return None  # not bullish

        entry_price = get_entry_execution_price(bar_close, 'LONG', pip, params)
        sl = zone.lower * (1 - params.sl_buffer_pct / 100)
        risk = entry_price - sl
        if risk <= 0:
            return None
        tp = entry_price + risk * params.rr_ratio

        return Signal(
            time=time, pair=pair, direction='LONG',
            entry_price=entry_price, sl_price=sl, tp_price=tp,
            zone_upper=zone.upper, zone_lower=zone.lower,
            zone_strength=zone.strength, zone_type='support',
        )

    elif zone.zone_type == 'resistance':
        # Bearish reversal candle at resistance -> SHORT
        if bar_close >= bar_open:
            return None  # not bearish

        entry_price = get_entry_execution_price(bar_close, 'SHORT', pip, params)
        sl = zone.upper * (1 + params.sl_buffer_pct / 100)
        risk = sl - entry_price
        if risk <= 0:
            return None
        tp = entry_price - risk * params.rr_ratio

        return Signal(
            time=time, pair=pair, direction='SHORT',
            entry_price=entry_price, sl_price=sl, tp_price=tp,
            zone_upper=zone.upper, zone_lower=zone.lower,
            zone_strength=zone.strength, zone_type='resistance',
        )

    return None


def check_momentum_filter(
    hourly_df: pd.DataFrame,
    bar_idx: int,
    zone: SRZone,
    params: StrategyParams,
) -> bool:
    """Check if recent candles show strong momentum INTO the zone.

    Per videos: skip entries where price is approaching the zone with
    very strong momentum / large candles (high break-through probability).

    Returns True if momentum is too strong (should SKIP the entry).
    """
    lookback = params.momentum_lookback
    if bar_idx < lookback:
        return False

    strong_count = 0
    for j in range(bar_idx - lookback, bar_idx):
        row = hourly_df.iloc[j]
        candle_range = abs(row['High'] - row['Low'])
        if candle_range == 0:
            continue
        body = abs(row['Close'] - row['Open'])
        body_ratio = body / candle_range

        # Strong candle = large body relative to range
        if body_ratio >= params.momentum_threshold:
            # Check direction: is this momentum TOWARD the zone?
            if zone.zone_type == 'support' and row['Close'] < row['Open']:
                strong_count += 1  # strong bearish candle approaching support
            elif zone.zone_type == 'resistance' and row['Close'] > row['Open']:
                strong_count += 1  # strong bullish candle approaching resistance

    # If majority of recent candles are strong momentum toward zone, skip
    return strong_count >= lookback


def check_linger_filter(
    hourly_df: pd.DataFrame,
    bar_idx: int,
    zone: SRZone,
    params: StrategyParams,
) -> bool:
    """Check if price has been lingering at the zone (no quick bounce).

    Returns True if price lingered too long (should SKIP the entry).
    """
    if params.max_linger_bars <= 0:
        return False

    start = max(0, bar_idx - params.linger_lookback)
    overlap_count = 0
    for j in range(start, bar_idx):
        row = hourly_df.iloc[j]
        if row['Low'] <= zone.upper and row['High'] >= zone.lower:
            overlap_count += 1

    return overlap_count >= params.max_linger_bars


def check_zone_exhaustion(
    hourly_df: pd.DataFrame,
    bar_idx: int,
    zone: SRZone,
    params: StrategyParams,
) -> bool:
    """Check if zone has been tested too many times recently.

    Counts distinct visits (transitions from not-in-zone to in-zone).
    Returns True if exhausted (should SKIP the entry).
    """
    if params.zone_exhaustion_threshold <= 0:
        return False

    start = max(0, bar_idx - params.zone_exhaustion_lookback)
    visits = 0
    was_in_zone = False
    for j in range(start, bar_idx):
        row = hourly_df.iloc[j]
        in_zone = row['Low'] <= zone.upper and row['High'] >= zone.lower
        if in_zone and not was_in_zone:
            visits += 1
        was_in_zone = in_zone

    return visits >= params.zone_exhaustion_threshold


def score_signal_quality(
    zone: SRZone,
    bar_open: float,
    bar_close: float,
    bar_high: float,
    bar_low: float,
    hourly_df: pd.DataFrame,
    bar_idx: int,
    params: StrategyParams,
) -> float:
    """Score signal quality from 0.0 to 1.0.

    Factors (weighted average):
    - Zone touches (0.4): min(touches/8, 1.0)
    - Candle body quality (0.3): body/range ratio
    - Freshness (0.2): inverse of recent zone visits
    - Zone width tightness (0.1): tighter = better defined
    """
    # Zone touches: cap at 8
    touch_score = min(zone.touches / 8.0, 1.0)

    # Candle body quality
    candle_range = abs(bar_high - bar_low)
    body_score = abs(bar_close - bar_open) / candle_range if candle_range > 0 else 0.0

    # Freshness: count recent visits and invert
    lookback = params.zone_exhaustion_lookback if params.zone_exhaustion_lookback > 0 else 50
    start = max(0, bar_idx - lookback)
    visits = 0
    was_in_zone = False
    for j in range(start, bar_idx):
        row = hourly_df.iloc[j]
        in_zone = row['Low'] <= zone.upper and row['High'] >= zone.lower
        if in_zone and not was_in_zone:
            visits += 1
        was_in_zone = in_zone
    freshness_score = max(0.0, 1.0 - visits / 5.0)

    # Zone width tightness (relative to midpoint)
    zone_width = zone.upper - zone.lower
    relative_width = zone_width / zone.midpoint if zone.midpoint > 0 else 0.0
    width_score = max(0.0, 1.0 - relative_width / 0.01)

    quality = 0.4 * touch_score + 0.3 * body_score + 0.2 * freshness_score + 0.1 * width_score
    return max(0.0, min(1.0, quality))


def get_tradeable_zones(
    zones: List[SRZone],
    current_price: float,
) -> tuple[Optional[SRZone], Optional[SRZone]]:
    """Return the nearest major support/resistance zones for the current price.

    Zone selection is based on the zone's assigned type, not only on whether the
    current price is above or below the midpoint. That keeps a zone eligible even
    when price has already penetrated into it, which is required by the entry
    rules.
    """

    major_zones = [zone for zone in zones if zone.strength == 'major']
    support = _select_nearest_zone_by_type(major_zones, 'support', current_price)
    resistance = _select_nearest_zone_by_type(major_zones, 'resistance', current_price)
    return support, resistance


def _select_nearest_zone_by_type(
    zones: List[SRZone],
    zone_type: str,
    current_price: float,
) -> Optional[SRZone]:
    """Pick the nearest zone of the requested type for the current price."""

    typed = [zone for zone in zones if zone.zone_type == zone_type]
    if not typed:
        return None

    if zone_type == 'support':
        below = [zone for zone in typed if zone.midpoint <= current_price]
        if below:
            return max(below, key=lambda zone: zone.midpoint)
    else:
        above = [zone for zone in typed if zone.midpoint >= current_price]
        if above:
            return min(above, key=lambda zone: zone.midpoint)

    return min(typed, key=lambda zone: abs(zone.midpoint - current_price))


def is_entry_time_blocked(
    entry_time: pd.Timestamp,
    params: StrategyParams,
) -> bool:
    """Return True when the strategy blocks new entries at this timestamp."""

    if not params.use_time_filters:
        return False

    entry_hour = entry_time.hour if hasattr(entry_time, 'hour') else 0
    entry_weekday = entry_time.weekday() if hasattr(entry_time, 'weekday') else 0
    return entry_hour in params.blocked_hours or entry_weekday in params.blocked_days


def is_pair_direction_blocked(
    pair: str,
    direction: str,
    params: StrategyParams,
) -> bool:
    """Return True when the pair-direction historical filter blocks an entry."""

    return params.use_pair_direction_filter and (pair, direction) in BLOCKED_PAIR_DIRECTIONS


def is_pair_fully_blocked(pair: str, params: StrategyParams) -> bool:
    """Return True when both directions for the pair are blocked."""

    return (
        params.use_pair_direction_filter
        and is_pair_direction_blocked(pair, 'LONG', params)
        and is_pair_direction_blocked(pair, 'SHORT', params)
    )


def select_entry_signal(
    hourly_df: pd.DataFrame,
    bar_idx: int,
    pair: str,
    params: StrategyParams,
    support_zone: Optional[SRZone],
    resistance_zone: Optional[SRZone],
) -> Optional[Signal]:
    """Evaluate the full shared entry rule-set for one hourly bar."""

    current_time = hourly_df.index[bar_idx]
    if is_entry_time_blocked(current_time, params):
        return None

    row = hourly_df.iloc[bar_idx]
    for zone in (support_zone, resistance_zone):
        if zone is None:
            continue
        if check_momentum_filter(hourly_df, bar_idx, zone, params):
            continue
        if check_linger_filter(hourly_df, bar_idx, zone, params):
            continue
        if check_zone_exhaustion(hourly_df, bar_idx, zone, params):
            continue

        signal = generate_signal(
            bar_open=row['Open'],
            bar_close=row['Close'],
            bar_high=row['High'],
            bar_low=row['Low'],
            zone=zone,
            pair=pair,
            time=current_time,
            params=params,
        )
        if signal is None:
            continue
        if is_pair_direction_blocked(pair, signal.direction, params):
            continue
        signal.quality_score = score_signal_quality(
            zone, row['Open'], row['Close'], row['High'], row['Low'],
            hourly_df, bar_idx, params,
        )
        return signal

    return None


def build_trade_from_signal(
    signal: Signal,
    *,
    entry_price: float | None = None,
    entry_time: pd.Timestamp | None = None,
    sl_price: float | None = None,
    tp_price: float | None = None,
) -> Trade:
    """Create an open trade object from a generated signal."""

    actual_entry_price = float(signal.entry_price if entry_price is None else entry_price)
    actual_entry_time = signal.time if entry_time is None else pd.Timestamp(entry_time)
    actual_sl_price = float(signal.sl_price if sl_price is None else sl_price)
    actual_tp_price = float(signal.tp_price if tp_price is None else tp_price)

    if signal.direction == 'LONG':
        risk = actual_entry_price - actual_sl_price
    else:
        risk = actual_sl_price - actual_entry_price

    return Trade(
        entry_time=actual_entry_time,
        entry_price=actual_entry_price,
        direction=signal.direction,
        sl_price=actual_sl_price,
        tp_price=actual_tp_price,
        zone_upper=signal.zone_upper,
        zone_lower=signal.zone_lower,
        zone_strength=signal.zone_strength,
        risk=risk,
        quality_score=signal.quality_score,
    )


def check_price_exit(
    trade: Trade,
    high_price: float,
    low_price: float,
    close_price: float,
    *,
    params: StrategyParams,
    pip: float,
    bar_time: pd.Timestamp | None = None,
    bars_held: int | None = None,
    allow_friday: bool = False,
    allow_sideways: bool = False,
    allow_time: bool = False,
) -> Optional[tuple[str, float]]:
    """Shared price-based exit engine used by both bar and tick paths."""

    early_exit_r = max(params.early_exit_r, 0.0)
    half_spread = get_half_spread_price(pip, params)
    market_exit = get_market_exit_price(close_price, trade.direction, pip, params)

    if trade.direction == 'LONG':
        tp_hit = high_price >= trade.tp_price + half_spread
        sl_hit = low_price <= trade.sl_price + half_spread

        if tp_hit and sl_hit:
            return ('SL', get_stop_exit_price(trade.sl_price, trade.direction, pip, params))
        if tp_hit:
            return ('TP', trade.tp_price)

        if allow_friday and bar_time is not None and hasattr(bar_time, 'weekday') and bar_time.weekday() == 4:
            if market_exit > trade.entry_price:
                tp_dist = trade.tp_price - trade.entry_price
                if tp_dist > 0:
                    current_progress = (market_exit - trade.entry_price) / tp_dist
                    if current_progress >= params.friday_tp_pct:
                        return ('FRIDAY', market_exit)

        if sl_hit:
            return ('SL', get_stop_exit_price(trade.sl_price, trade.direction, pip, params))

        loss_r = ((trade.entry_price - market_exit) / trade.risk) if trade.risk > 0 else 0.0
        if close_price < trade.zone_lower or loss_r >= early_exit_r:
            return ('EARLY_EXIT', market_exit)

        if allow_sideways and bars_held is not None and bars_held >= params.sideways_bars:
            tp_dist = trade.tp_price - trade.entry_price
            if tp_dist > 0:
                progress = max(0.0, (market_exit - trade.entry_price) / tp_dist)
                if progress < params.sideways_threshold:
                    return ('SIDEWAYS', market_exit)

        if allow_time and bars_held is not None and bars_held >= params.max_hold_bars:
            return ('TIME', market_exit)

    else:
        tp_hit = low_price <= trade.tp_price - half_spread
        sl_hit = high_price >= trade.sl_price - half_spread

        if tp_hit and sl_hit:
            return ('SL', get_stop_exit_price(trade.sl_price, trade.direction, pip, params))
        if tp_hit:
            return ('TP', trade.tp_price)

        if allow_friday and bar_time is not None and hasattr(bar_time, 'weekday') and bar_time.weekday() == 4:
            if market_exit < trade.entry_price:
                tp_dist = trade.entry_price - trade.tp_price
                if tp_dist > 0:
                    current_progress = (trade.entry_price - market_exit) / tp_dist
                    if current_progress >= params.friday_tp_pct:
                        return ('FRIDAY', market_exit)

        if sl_hit:
            return ('SL', get_stop_exit_price(trade.sl_price, trade.direction, pip, params))

        loss_r = ((market_exit - trade.entry_price) / trade.risk) if trade.risk > 0 else 0.0
        if close_price > trade.zone_upper or loss_r >= early_exit_r:
            return ('EARLY_EXIT', market_exit)

        if allow_sideways and bars_held is not None and bars_held >= params.sideways_bars:
            tp_dist = trade.entry_price - trade.tp_price
            if tp_dist > 0:
                progress = max(0.0, (trade.entry_price - market_exit) / tp_dist)
                if progress < params.sideways_threshold:
                    return ('SIDEWAYS', market_exit)

        if allow_time and bars_held is not None and bars_held >= params.max_hold_bars:
            return ('TIME', market_exit)

    return None


def check_exit(
    trade: Trade,
    bar_high: float,
    bar_low: float,
    bar_close: float,
    bar_time: pd.Timestamp,
    bars_held: int,
    params: StrategyParams,
    pip: float,
    progress_toward_tp: float = 0.0,
) -> Optional[tuple[str, float]]:
    """Check if a trade should be exited.

    Enhanced exit rules (from all 30 videos):
    1. TP hit -> close at TP (hold winners)
    2. Friday close -> if winning and 70%+ to TP on Friday
    3. SL hit -> close at SL (emergency protection)
    4. EARLY EXIT: price breaks through zone -> close at partial loss
    5. SIDEWAYS: no progress after ~15 bars -> close at current price
    6. TIME: held too long (~72 bars / 3 days) without TP -> close

    Uses conservative midpoint-bar execution assumptions:
    - spread is modeled explicitly on entries and market exits
    - TP requires the midpoint to clear half-spread beyond the target
    - SL can trigger half-spread before the midpoint touches the stop level
    - if both TP and SL print in the same bar, resolve to SL

    Returns:
        (exit_reason, exit_price) tuple, or None if trade stays open
    """
    del progress_toward_tp  # legacy arg retained for compatibility
    return check_price_exit(
        trade,
        bar_high,
        bar_low,
        bar_close,
        params=params,
        pip=pip,
        bar_time=bar_time,
        bars_held=bars_held,
        allow_friday=True,
        allow_sideways=True,
        allow_time=True,
    )
